### PR TITLE
MSQL_Task4

### PR DESCRIPTION
**Pull request by wi9916**

### CODE REVIEW

**Comment by wi9916** [comment]
Start Task4 MSQL

**Comment by wi9916** [comment]
Start serhii 2

**Review by mihail-saharilenko — CHANGES_REQUESTED** [review]
Procedure is ok. However, your function is not. On the previous lecture I told that you shouldn't use any hardcoded tables, and you should have input parameter TableName in function. Please update your function to make it be able to generate new ID for any table.

**Comment by wi9916** [comment]
Rewrite

**Review by mihail-saharilenko — APPROVED** [review]

**Pull request merged**
